services:
  mysql:
    image: mysql:latest
    container_name: my-sql-default
    ports:
      - "3306:3306"
    network_mode: bridge
    environment:
        MYSQL_ROOT_PASSWORD: 123456789
    volumes:
      - ./db-scripts/mysql-create-db.sql:/docker-entrypoint-initdb.d/1-ddl.sql
      - ./db-scripts/mysql-init.sql:/docker-entrypoint-initdb.d/2-dml.sql 