package com.fitech.app.admin.application.dto;

import java.math.BigDecimal;
import io.swagger.v3.oas.annotations.media.Schema;

@Schema(description = "DTO for admin payment summary and platform revenue overview")
public class AdminPaymentSummaryDTO {
    @Schema(description = "Total revenue generated by the platform", example = "15000.00")
    private BigDecimal totalRevenue;
    
    @Schema(description = "Number of pending payments", example = "5")
    private Integer pendingPayments;
    
    @Schema(description = "Revenue from completed but not yet collected payments", example = "2500.00")
    private BigDecimal completedRevenue;
    
    @Schema(description = "Total commission earned by platform", example = "750.00")
    private BigDecimal totalCommission;

    public AdminPaymentSummaryDTO() {}

    public AdminPaymentSummaryDTO(BigDecimal totalRevenue, Integer pendingPayments, 
                                 BigDecimal completedRevenue, BigDecimal totalCommission) {
        this.totalRevenue = totalRevenue;
        this.pendingPayments = pendingPayments;
        this.completedRevenue = completedRevenue;
        this.totalCommission = totalCommission;
    }

    // Getters and Setters
    public BigDecimal getTotalRevenue() { 
        return totalRevenue; 
    }
    
    public void setTotalRevenue(BigDecimal totalRevenue) { 
        this.totalRevenue = totalRevenue; 
    }

    public Integer getPendingPayments() { 
        return pendingPayments; 
    }
    
    public void setPendingPayments(Integer pendingPayments) { 
        this.pendingPayments = pendingPayments; 
    }

    public BigDecimal getCompletedRevenue() { 
        return completedRevenue; 
    }
    
    public void setCompletedRevenue(BigDecimal completedRevenue) { 
        this.completedRevenue = completedRevenue; 
    }

    public BigDecimal getTotalCommission() { 
        return totalCommission; 
    }
    
    public void setTotalCommission(BigDecimal totalCommission) { 
        this.totalCommission = totalCommission; 
    }
} 